ALTER TABLE semesters
    ALTER COLUMN start_date SET NOT NULL,
    ALTER COLUMN end_date SET NOT NULL;

ALTER TABLE semesters
    ADD CONSTRAINT CK_semesters_date_order CHECK (end_date >= start_date),
    ADD CONSTRAINT CK_semesters_term_month_window CHECK (
        (name ILIKE 'Spring%' AND EXTRACT(MONTH FROM start_date) = 1 AND EXTRACT(MONTH FROM end_date) = 4)
        OR (name ILIKE 'Summer%' AND EXTRACT(MONTH FROM start_date) = 5 AND EXTRACT(MONTH FROM end_date) = 8)
        OR (name ILIKE 'Fall%' AND EXTRACT(MONTH FROM start_date) = 9 AND EXTRACT(MONTH FROM end_date) = 12)
    );

CREATE TABLE semester_subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    semester_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    CONSTRAINT PK_semester_subjects PRIMARY KEY (id),
    CONSTRAINT UQ_semester_subjects_semester_subject UNIQUE (semester_id, subject_id),
    CONSTRAINT FK_semester_subjects_semesters FOREIGN KEY (semester_id) REFERENCES semesters(id),
    CONSTRAINT FK_semester_subjects_subjects FOREIGN KEY (subject_id) REFERENCES subjects(id),
    CONSTRAINT CK_semester_subjects_date_order CHECK (end_date >= start_date),
    CONSTRAINT CK_semester_subjects_max_duration CHECK (end_date <= start_date + INTERVAL '3 months')
);

CREATE INDEX IX_semester_subjects_semester_id ON semester_subjects(semester_id);
CREATE INDEX IX_semester_subjects_subject_id ON semester_subjects(subject_id);

CREATE OR REPLACE FUNCTION validate_semester_subject_dates()
RETURNS TRIGGER AS $$
DECLARE
    semester_start DATE;
    semester_end DATE;
BEGIN
    SELECT start_date, end_date
    INTO semester_start, semester_end
    FROM semesters
    WHERE id = NEW.semester_id;

    IF semester_start IS NULL THEN
        RETURN NEW;
    END IF;

    IF NEW.start_date < semester_start OR NEW.end_date > semester_end THEN
        RAISE EXCEPTION 'semester subject dates must stay within semester dates';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM schedule existing
        WHERE existing.semester_id = NEW.semester_id
          AND existing.subject_id = NEW.subject_id
          AND (existing.study_date < NEW.start_date OR existing.study_date > NEW.end_date)
    ) THEN
        RAISE EXCEPTION 'schedule dates must stay within semester subject dates';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TR_semester_subjects_validate_dates
BEFORE INSERT OR UPDATE OF semester_id, subject_id, start_date, end_date
ON semester_subjects
FOR EACH ROW
EXECUTE FUNCTION validate_semester_subject_dates();

WITH offered AS (
    SELECT DISTINCT semester_id, subject_id
    FROM student_grades
    UNION
    SELECT DISTINCT semester_id, subject_id
    FROM schedule
),
schedule_bounds AS (
    SELECT
        semester_id,
        subject_id,
        MIN(study_date) AS min_study_date,
        MAX(study_date) AS max_study_date
    FROM schedule
    GROUP BY semester_id, subject_id
),
course_starts AS (
    SELECT
        offered.semester_id,
        offered.subject_id,
        CASE
            WHEN schedule_bounds.min_study_date IS NULL THEN semester.start_date
            ELSE GREATEST(
                semester.start_date,
                LEAST(schedule_bounds.min_study_date, (semester.end_date - INTERVAL '3 months')::DATE)
            )
        END AS start_date,
        semester.end_date AS semester_end_date,
        schedule_bounds.max_study_date
    FROM offered
    JOIN semesters semester ON semester.id = offered.semester_id
    LEFT JOIN schedule_bounds
        ON schedule_bounds.semester_id = offered.semester_id
       AND schedule_bounds.subject_id = offered.subject_id
)
INSERT INTO semester_subjects (
    semester_id,
    subject_id,
    start_date,
    end_date
)
SELECT
    semester_id,
    subject_id,
    start_date,
    LEAST(
        semester_end_date,
        GREATEST(
            COALESCE(max_study_date, start_date),
            (start_date + INTERVAL '3 months')::DATE
        )
    )
FROM course_starts
ON CONFLICT (semester_id, subject_id) DO UPDATE SET
    start_date = EXCLUDED.start_date,
    end_date = EXCLUDED.end_date;

ALTER TABLE student_grades
    ADD CONSTRAINT FK_student_grades_semester_subjects
    FOREIGN KEY (semester_id, subject_id) REFERENCES semester_subjects(semester_id, subject_id);

ALTER TABLE schedule
    ADD CONSTRAINT FK_schedule_semester_subjects
    FOREIGN KEY (semester_id, subject_id) REFERENCES semester_subjects(semester_id, subject_id);

CREATE OR REPLACE FUNCTION validate_schedule_course_date()
RETURNS TRIGGER AS $$
DECLARE
    course_start DATE;
    course_end DATE;
BEGIN
    SELECT start_date, end_date
    INTO course_start, course_end
    FROM semester_subjects
    WHERE semester_id = NEW.semester_id
      AND subject_id = NEW.subject_id;

    IF course_start IS NULL THEN
        RETURN NEW;
    END IF;

    IF NEW.study_date < course_start OR NEW.study_date > course_end THEN
        RAISE EXCEPTION 'schedule date must stay within semester subject dates';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TR_schedule_validate_course_date
BEFORE INSERT OR UPDATE OF semester_id, subject_id, study_date
ON schedule
FOR EACH ROW
EXECUTE FUNCTION validate_schedule_course_date();

CREATE OR REPLACE FUNCTION validate_semester_update_keeps_subject_dates()
RETURNS TRIGGER AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM semester_subjects existing
        WHERE existing.semester_id = NEW.id
          AND (existing.start_date < NEW.start_date OR existing.end_date > NEW.end_date)
    ) THEN
        RAISE EXCEPTION 'semester dates must contain existing semester subject dates';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TR_semesters_validate_subject_dates
BEFORE UPDATE OF start_date, end_date
ON semesters
FOR EACH ROW
EXECUTE FUNCTION validate_semester_update_keeps_subject_dates();
