CREATE TABLE student_subject_enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    semester_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_student_subject_enrollments PRIMARY KEY (id),
    CONSTRAINT UQ_student_subject_enrollments UNIQUE (user_id, semester_id, subject_id),
    CONSTRAINT FK_student_subject_enrollments_users
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT FK_student_subject_enrollments_semester_subjects
        FOREIGN KEY (semester_id, subject_id)
        REFERENCES semester_subjects(semester_id, subject_id) ON DELETE CASCADE
);

CREATE INDEX IX_student_subject_enrollments_user_semester
    ON student_subject_enrollments(user_id, semester_id);

INSERT INTO student_subject_enrollments (user_id, semester_id, subject_id)
SELECT DISTINCT user_id, semester_id, subject_id
FROM student_grades
ON CONFLICT (user_id, semester_id, subject_id) DO NOTHING;
