INSERT INTO roles (role_name) VALUES
    ('TEACHER')
ON CONFLICT (role_name) DO NOTHING;

INSERT INTO permission (permission_name, description) VALUES
    ('GRADE_READ', 'View student grades'),
    ('GRADE_WRITE', 'Create and update student grades')
ON CONFLICT (permission_name) DO NOTHING;

INSERT INTO user_role (user_id, role_id)
SELECT user_role.user_id, teacher_role.id
FROM user_role
JOIN roles lecturer_role ON lecturer_role.id = user_role.role_id
CROSS JOIN roles teacher_role
WHERE lecturer_role.role_name = 'LECTURER'
  AND teacher_role.role_name = 'TEACHER'
ON CONFLICT (user_id, role_id) DO NOTHING;

DELETE FROM role_permission
USING roles, permission
WHERE role_permission.role_id = roles.id
  AND role_permission.permission_id = permission.id
  AND roles.role_name = 'ADMIN'
  AND permission.permission_name = 'GRADE_WRITE';

INSERT INTO role_permission (role_id, permission_id)
SELECT roles.id, permission.id
FROM roles
JOIN permission ON permission.permission_name IN ('GRADE_READ', 'GRADE_WRITE')
WHERE roles.role_name = 'TEACHER'
ON CONFLICT (role_id, permission_id) DO NOTHING;

CREATE TABLE teacher_subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    teacher_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_teacher_subjects PRIMARY KEY (id),
    CONSTRAINT UQ_teacher_subjects_teacher_subject UNIQUE (teacher_id, subject_id),
    CONSTRAINT FK_teacher_subjects_users
        FOREIGN KEY (teacher_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT FK_teacher_subjects_subjects
        FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE
);

CREATE INDEX IX_teacher_subjects_teacher_id
    ON teacher_subjects(teacher_id);

CREATE INDEX IX_teacher_subjects_subject_id
    ON teacher_subjects(subject_id);
