INSERT INTO roles (role_name) VALUES
    ('PARENT')
ON CONFLICT (role_name) DO NOTHING;

INSERT INTO permission (permission_name, description) VALUES
    ('CHILD_READ', 'View linked students'),
    ('CHILD_GRADE_READ', 'View linked student grades'),
    ('CHILD_SCHEDULE_READ', 'View linked student schedules')
ON CONFLICT (permission_name) DO NOTHING;

INSERT INTO role_permission (role_id, permission_id)
SELECT roles.id, permission.id
FROM roles
JOIN permission ON permission.permission_name IN (
    'CHILD_READ',
    'CHILD_GRADE_READ',
    'CHILD_SCHEDULE_READ'
)
WHERE roles.role_name = 'PARENT'
ON CONFLICT (role_id, permission_id) DO NOTHING;

CREATE TABLE parent_students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    parent_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    linked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_parent_students PRIMARY KEY (id),
    CONSTRAINT UQ_parent_students_parent_student UNIQUE (parent_id, student_id),
    CONSTRAINT FK_parent_students_parent
        FOREIGN KEY (parent_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT FK_parent_students_student
        FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IX_parent_students_parent_id
    ON parent_students(parent_id);

CREATE INDEX IX_parent_students_student_id
    ON parent_students(student_id);

ALTER TABLE schedule
    ADD COLUMN teacher_id BIGINT NULL;

ALTER TABLE schedule
    ADD CONSTRAINT FK_schedule_teacher_users
        FOREIGN KEY (teacher_id) REFERENCES users(id) ON DELETE SET NULL;

CREATE INDEX IX_schedule_teacher_id
    ON schedule(teacher_id);

CREATE INDEX IX_schedule_teacher_date
    ON schedule(teacher_id, study_date, start_time);
