INSERT INTO roles (role_name) VALUES
    ('SUBJECT_TEACHER'),
    ('HOMEROOM_TEACHER')
ON CONFLICT (role_name) DO NOTHING;

INSERT INTO permission (permission_name, description) VALUES
    ('APPLICATION_READ', 'View applications for assigned homeroom class'),
    ('APPLICATION_REVIEW', 'Review applications for assigned homeroom class')
ON CONFLICT (permission_name) DO NOTHING;

INSERT INTO role_permission (role_id, permission_id)
SELECT roles.id, permission.id
FROM roles
JOIN permission ON permission.permission_name IN ('GRADE_READ', 'GRADE_WRITE')
WHERE roles.role_name = 'SUBJECT_TEACHER'
ON CONFLICT (role_id, permission_id) DO NOTHING;

INSERT INTO role_permission (role_id, permission_id)
SELECT roles.id, permission.id
FROM roles
JOIN permission ON permission.permission_name IN ('APPLICATION_READ', 'APPLICATION_REVIEW')
WHERE roles.role_name = 'HOMEROOM_TEACHER'
ON CONFLICT (role_id, permission_id) DO NOTHING;

INSERT INTO user_role (user_id, role_id)
SELECT user_role.user_id, subject_role.id
FROM user_role
JOIN roles teacher_role ON teacher_role.id = user_role.role_id
CROSS JOIN roles subject_role
WHERE teacher_role.role_name = 'TEACHER'
  AND subject_role.role_name = 'SUBJECT_TEACHER'
ON CONFLICT (user_id, role_id) DO NOTHING;

CREATE TABLE homeroom_teacher_classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    teacher_id BIGINT NOT NULL,
    class_name VARCHAR(50) NOT NULL,
    assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_homeroom_teacher_classes PRIMARY KEY (id),
    CONSTRAINT UQ_homeroom_teacher_classes_teacher UNIQUE (teacher_id),
    CONSTRAINT UQ_homeroom_teacher_classes_class UNIQUE (class_name),
    CONSTRAINT FK_homeroom_teacher_classes_users
        FOREIGN KEY (teacher_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IX_homeroom_teacher_classes_class_name
    ON homeroom_teacher_classes(class_name);

ALTER TABLE student_applications
    ADD COLUMN parent_id BIGINT NULL;

ALTER TABLE student_applications
    ADD CONSTRAINT FK_student_applications_parent_users
        FOREIGN KEY (parent_id) REFERENCES users(id) ON DELETE SET NULL;

CREATE INDEX IX_student_applications_parent_id
    ON student_applications(parent_id);

WITH seed_users (
    user_name,
    email,
    user_password,
    first_name,
    last_name,
    phone,
    class_name,
    status
) AS (
    VALUES (
        'homeroom01',
        'homeroom01@myfschool.local',
        '$2a$12$pnPwVNeJUPBsCOLZhwi/JO0YuNiI9jazKD37ef6jwM8qgd7FLHN2C',
        'Homeroom',
        'Teacher',
        '0902000003',
        NULL,
        'ACTIVE'
    )
)
INSERT INTO users (
    user_name,
    email,
    user_password,
    first_name,
    last_name,
    phone,
    class_name,
    status
)
SELECT
    seed_users.user_name,
    seed_users.email,
    seed_users.user_password,
    seed_users.first_name,
    seed_users.last_name,
    seed_users.phone,
    seed_users.class_name,
    seed_users.status
FROM seed_users
ON CONFLICT (user_name) DO UPDATE SET
    email = EXCLUDED.email,
    user_password = EXCLUDED.user_password,
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    phone = EXCLUDED.phone,
    class_name = EXCLUDED.class_name,
    status = EXCLUDED.status;

WITH role_links (user_name, role_name) AS (
    VALUES
        ('homeroom01', 'HOMEROOM_TEACHER')
)
INSERT INTO user_role (user_id, role_id)
SELECT users.id, roles.id
FROM role_links
JOIN users ON users.user_name = role_links.user_name
JOIN roles ON roles.role_name = role_links.role_name
ON CONFLICT (user_id, role_id) DO NOTHING;

INSERT INTO homeroom_teacher_classes (teacher_id, class_name)
SELECT users.id, 'SE1911-JV'
FROM users
WHERE users.user_name = 'homeroom01'
ON CONFLICT (teacher_id) DO UPDATE SET
    class_name = EXCLUDED.class_name;
