CREATE TABLE exam_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    semester_id BIGINT NOT NULL,
    exam_type VARCHAR(50) NOT NULL DEFAULT 'FINAL',
    exam_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    room VARCHAR(50) NULL,
    seat_number VARCHAR(20) NULL,
    proctor_name VARCHAR(100) NULL,
    note TEXT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_exam_schedules PRIMARY KEY (id),
    CONSTRAINT UQ_exam_schedules_user_subject_semester_type UNIQUE (user_id, subject_id, semester_id, exam_type),
    CONSTRAINT FK_exam_schedules_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT FK_exam_schedules_subjects FOREIGN KEY (subject_id) REFERENCES subjects(id),
    CONSTRAINT FK_exam_schedules_semesters FOREIGN KEY (semester_id) REFERENCES semesters(id),
    CONSTRAINT FK_exam_schedules_semester_subjects
        FOREIGN KEY (semester_id, subject_id) REFERENCES semester_subjects(semester_id, subject_id),
    CONSTRAINT CK_exam_schedules_time_order CHECK (end_time > start_time),
    CONSTRAINT CK_exam_schedules_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'CANCELLED'))
);

CREATE INDEX IX_exam_schedules_user_semester
    ON exam_schedules(user_id, semester_id);

CREATE INDEX IX_exam_schedules_exam_date
    ON exam_schedules(exam_date, start_time);

INSERT INTO permission (permission_name, description) VALUES
    ('EXAM_SCHEDULE_READ', 'View exam schedules'),
    ('EXAM_SCHEDULE_WRITE', 'Create and update exam schedules')
ON CONFLICT (permission_name) DO NOTHING;

INSERT INTO role_permission (role_id, permission_id)
SELECT roles.id, permission.id
FROM roles
CROSS JOIN permission
WHERE roles.role_name = 'ADMIN'
  AND permission.permission_name IN ('EXAM_SCHEDULE_READ', 'EXAM_SCHEDULE_WRITE')
ON CONFLICT (role_id, permission_id) DO NOTHING;

WITH target_students AS (
    SELECT
        users.id AS user_id,
        users.user_name,
        ROW_NUMBER() OVER (ORDER BY users.user_name) AS seat_index
    FROM users
    JOIN user_role ON user_role.user_id = users.id
    JOIN roles ON roles.id = user_role.role_id
    WHERE roles.role_name = 'STUDENT'
      AND users.status = 'ACTIVE'
      AND users.class_name = 'SE1911-JV'
),
target_semester AS (
    SELECT id AS semester_id
    FROM semesters
    WHERE name = 'Summer 2026'
),
exam_slots AS (
    SELECT *
    FROM (
        VALUES
            ('PRM393', 'FINAL', DATE '2026-08-10', TIME '07:30', TIME '09:00', 'BE-301', 'Nguyen Van A', 'Bring student card and laptop'),
            ('SWR302', 'FINAL', DATE '2026-08-11', TIME '09:30', TIME '11:00', 'BE-204', 'Tran Thi B', 'Requirement analysis written exam'),
            ('DBI202', 'FINAL', DATE '2026-08-12', TIME '07:30', TIME '09:00', 'BE-112', 'Le Van C', 'SQL and database design exam'),
            ('PRO192', 'FINAL', DATE '2026-08-13', TIME '13:30', TIME '15:00', 'BE-410', 'Pham Thi D', 'Java programming practical exam'),
            ('MLN111', 'FINAL', DATE '2026-08-14', TIME '09:30', TIME '11:00', 'BE-205', 'Tran Thi Mai', 'Written exam'),
            ('MSS301', 'FINAL', DATE '2026-08-15', TIME '07:30', TIME '09:00', 'BE-308', 'Dang Quoc Huy', 'Microservices final exam'),
            ('EXE201', 'FINAL', DATE '2026-08-16', TIME '13:30', TIME '15:00', 'BE-402', 'Hoang Minh Quan', 'Project defense schedule')
    ) AS slot_seed(subject_code, exam_type, exam_date, start_time, end_time, room, proctor_name, note)
),
resolved_slots AS (
    SELECT
        target_semester.semester_id,
        subjects.id AS subject_id,
        exam_slots.subject_code,
        exam_slots.exam_type,
        exam_slots.exam_date,
        exam_slots.start_time,
        exam_slots.end_time,
        exam_slots.room,
        exam_slots.proctor_name,
        exam_slots.note
    FROM exam_slots
    JOIN subjects ON subjects.subject_code = exam_slots.subject_code
    CROSS JOIN target_semester
    JOIN semester_subjects
        ON semester_subjects.semester_id = target_semester.semester_id
       AND semester_subjects.subject_id = subjects.id
    JOIN semesters
        ON semesters.id = target_semester.semester_id
       AND exam_slots.exam_date BETWEEN semesters.start_date AND semesters.end_date
)
INSERT INTO exam_schedules (
    user_id,
    subject_id,
    semester_id,
    exam_type,
    exam_date,
    start_time,
    end_time,
    room,
    seat_number,
    proctor_name,
    note,
    status
)
SELECT
    target_students.user_id,
    resolved_slots.subject_id,
    resolved_slots.semester_id,
    resolved_slots.exam_type,
    resolved_slots.exam_date,
    resolved_slots.start_time,
    resolved_slots.end_time,
    resolved_slots.room,
    'S' || LPAD(target_students.seat_index::TEXT, 2, '0'),
    resolved_slots.proctor_name,
    resolved_slots.note,
    'PUBLISHED'
FROM target_students
JOIN resolved_slots ON TRUE
JOIN student_subject_enrollments
    ON student_subject_enrollments.user_id = target_students.user_id
   AND student_subject_enrollments.semester_id = resolved_slots.semester_id
   AND student_subject_enrollments.subject_id = resolved_slots.subject_id
ON CONFLICT (user_id, subject_id, semester_id, exam_type) DO UPDATE SET
    exam_date = EXCLUDED.exam_date,
    start_time = EXCLUDED.start_time,
    end_time = EXCLUDED.end_time,
    room = EXCLUDED.room,
    seat_number = EXCLUDED.seat_number,
    proctor_name = EXCLUDED.proctor_name,
    note = EXCLUDED.note,
    status = EXCLUDED.status;

SELECT setval(
    pg_get_serial_sequence('exam_schedules', 'id'),
    GREATEST(COALESCE((SELECT MAX(id) FROM exam_schedules), 1), 1)
);
