CREATE TABLE attendance_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    schedule_id BIGINT NULL,
    user_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    semester_id BIGINT NOT NULL,
    attendance_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PRESENT',
    note TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_attendance_records PRIMARY KEY (id),
    CONSTRAINT UQ_attendance_records_schedule UNIQUE (schedule_id),
    CONSTRAINT FK_attendance_records_schedule FOREIGN KEY (schedule_id) REFERENCES schedule(id) ON DELETE CASCADE,
    CONSTRAINT FK_attendance_records_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT FK_attendance_records_subjects FOREIGN KEY (subject_id) REFERENCES subjects(id),
    CONSTRAINT FK_attendance_records_semesters FOREIGN KEY (semester_id) REFERENCES semesters(id),
    CONSTRAINT FK_attendance_records_semester_subjects
        FOREIGN KEY (semester_id, subject_id) REFERENCES semester_subjects(semester_id, subject_id),
    CONSTRAINT CK_attendance_records_status CHECK (status IN ('PRESENT', 'ABSENT', 'LATE', 'EXCUSED'))
);

CREATE INDEX IX_attendance_records_user_semester
    ON attendance_records(user_id, semester_id);

CREATE INDEX IX_attendance_records_user_subject
    ON attendance_records(user_id, semester_id, subject_id);

INSERT INTO permission (permission_name, description) VALUES
    ('ATTENDANCE_READ', 'View attendance reports'),
    ('ATTENDANCE_WRITE', 'Create and update attendance records')
ON CONFLICT (permission_name) DO NOTHING;

INSERT INTO role_permission (role_id, permission_id)
SELECT roles.id, permission.id
FROM roles
CROSS JOIN permission
WHERE roles.role_name = 'ADMIN'
  AND permission.permission_name IN ('ATTENDANCE_READ', 'ATTENDANCE_WRITE')
ON CONFLICT (role_id, permission_id) DO NOTHING;

WITH scheduled_lessons AS (
    SELECT
        schedule.id AS schedule_id,
        schedule.user_id,
        schedule.subject_id,
        schedule.semester_id,
        schedule.study_date AS attendance_date,
        ROW_NUMBER() OVER (
            PARTITION BY schedule.user_id, schedule.semester_id, schedule.subject_id
            ORDER BY schedule.study_date, schedule.start_time, schedule.id
        ) AS lesson_index
    FROM schedule
)
INSERT INTO attendance_records (
    schedule_id,
    user_id,
    subject_id,
    semester_id,
    attendance_date,
    status,
    note
)
SELECT
    scheduled_lessons.schedule_id,
    scheduled_lessons.user_id,
    scheduled_lessons.subject_id,
    scheduled_lessons.semester_id,
    scheduled_lessons.attendance_date,
    CASE
        WHEN MOD(scheduled_lessons.lesson_index + scheduled_lessons.user_id + scheduled_lessons.subject_id, 6) = 0 THEN 'ABSENT'
        WHEN MOD(scheduled_lessons.lesson_index + scheduled_lessons.subject_id, 4) = 0 THEN 'LATE'
        ELSE 'PRESENT'
    END AS status,
    CASE
        WHEN MOD(scheduled_lessons.lesson_index + scheduled_lessons.user_id + scheduled_lessons.subject_id, 6) = 0 THEN 'Absent from class'
        WHEN MOD(scheduled_lessons.lesson_index + scheduled_lessons.subject_id, 4) = 0 THEN 'Arrived late'
        ELSE NULL
    END AS note
FROM scheduled_lessons
ON CONFLICT (schedule_id) DO UPDATE SET
    user_id = EXCLUDED.user_id,
    subject_id = EXCLUDED.subject_id,
    semester_id = EXCLUDED.semester_id,
    attendance_date = EXCLUDED.attendance_date,
    status = EXCLUDED.status,
    note = EXCLUDED.note;

SELECT setval(
    pg_get_serial_sequence('attendance_records', 'id'),
    GREATEST(COALESCE((SELECT MAX(id) FROM attendance_records), 1), 1)
);
