CREATE TABLE student_grade_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_grade_id BIGINT NOT NULL,
    grade_category VARCHAR(100) NOT NULL,
    grade_item VARCHAR(100) NOT NULL,
    weight DECIMAL(5,2) NULL,
    value VARCHAR(50) NULL,
    display_order INT NOT NULL CONSTRAINT DF_student_grade_items_display_order DEFAULT 0,
    CONSTRAINT PK_student_grade_items PRIMARY KEY (id),
    CONSTRAINT FK_student_grade_items_student_grades FOREIGN KEY (student_grade_id) REFERENCES student_grades(id) ON DELETE CASCADE
);

CREATE INDEX IX_student_grade_items_student_grade_id ON student_grade_items(student_grade_id);

INSERT INTO student_grade_items (
    student_grade_id,
    grade_category,
    grade_item,
    weight,
    value,
    display_order
)
SELECT grade.id, seed.grade_category, seed.grade_item, seed.weight, seed.value, seed.display_order
FROM student_grades grade
JOIN subjects subject ON subject.id = grade.subject_id
JOIN (
    VALUES
        ('MLN111', 'Participation', 'Participation', 10.00, '9', 10),
        ('MLN111', 'Participation', 'Total', 10.00, '9', 20),
        ('MLN111', 'Progress tests', 'Progress tests', 20.00, '3.2', 30),
        ('MLN111', 'Progress tests', 'Total', 20.00, '3.2', 40),
        ('MLN111', 'Assignment', 'Assignment 1', 20.00, '8.3', 50),
        ('MLN111', 'Assignment', 'Assignment 2', 20.00, '9', 60),
        ('MLN111', 'Assignment', 'Total', 40.00, '8.7', 70),
        ('MLN111', 'Final exam', 'Final exam', 30.00, '7.5', 80),
        ('MLN111', 'Final exam', 'Total', 30.00, '7.5', 90),
        ('MLN111', 'Final exam Resit', 'Final exam Resit', 30.00, NULL, 100),
        ('MLN111', 'Final exam Resit', 'Total', 30.00, NULL, 110),
        ('MLN111', 'Course total', 'Average', NULL, '7.3', 120),
        ('MLN111', 'Course total', 'Status', NULL, 'Passed', 130),
        ('EXE201', 'Outcome 2', 'Outcome 2', 20.00, NULL, 10),
        ('EXE201', 'Outcome 2', 'Total', 20.00, NULL, 20),
        ('EXE201', 'Outcome 1', 'Outcome 1', 40.00, NULL, 30),
        ('EXE201', 'Outcome 1', 'Total', 40.00, NULL, 40),
        ('EXE201', 'Outcome 3', 'Outcome 3', 40.00, NULL, 50),
        ('EXE201', 'Outcome 3', 'Total', 40.00, NULL, 60),
        ('EXE201', 'Course total', 'Average', NULL, '0.0', 70),
        ('EXE201', 'Course total', 'Status', NULL, 'Studying', 80),
        ('MSS301', 'Assignment', 'Assignment', 30.00, '0.0', 10),
        ('MSS301', 'Lab', 'Lab', 20.00, '0.0', 20),
        ('MSS301', 'Final exam', 'Final exam', 50.00, '0.0', 30),
        ('MSS301', 'Course total', 'Average', NULL, '0.0', 40),
        ('MSS301', 'Course total', 'Status', NULL, 'Studying', 50),
        ('PRM393', 'Lab', 'Lab', 30.00, '0.0', 10),
        ('PRM393', 'Progress test', 'Progress test', 20.00, '0.0', 20),
        ('PRM393', 'Final exam', 'Final exam', 50.00, '0.0', 30),
        ('PRM393', 'Course total', 'Average', NULL, '0.0', 40),
        ('PRM393', 'Course total', 'Status', NULL, 'Studying', 50)
) AS seed(subject_code, grade_category, grade_item, weight, value, display_order)
    ON seed.subject_code = subject.subject_code
WHERE grade.user_id = 1
  AND NOT EXISTS (
      SELECT 1
      FROM student_grade_items existing
      WHERE existing.student_grade_id = grade.id
        AND existing.grade_category = seed.grade_category
        AND existing.grade_item = seed.grade_item
  );
