CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name VARCHAR(50) NOT NULL,
    CONSTRAINT PK_roles PRIMARY KEY (id),
    CONSTRAINT UQ_roles_role_name UNIQUE (role_name)
);

CREATE TABLE permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    permission_name VARCHAR(100) NOT NULL,
    description TEXT NULL,
    CONSTRAINT PK_permissions PRIMARY KEY (id),
    CONSTRAINT UQ_permissions_permission_name UNIQUE (permission_name)
);

CREATE TABLE user_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT PK_user_role PRIMARY KEY (id),
    CONSTRAINT UQ_user_role_user_id_role_id UNIQUE (user_id, role_id),
    CONSTRAINT FK_user_role_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT FK_user_role_roles FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE TABLE role_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    CONSTRAINT PK_role_permission PRIMARY KEY (id),
    CONSTRAINT UQ_role_permission_role_id_permission_id UNIQUE (role_id, permission_id),
    CONSTRAINT FK_role_permission_roles FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
    CONSTRAINT FK_role_permission_permissions FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
);

INSERT INTO roles (role_name) VALUES
    ('ADMIN'),
    ('LECTURER'),
    ('STUDENT')
ON CONFLICT (role_name) DO NOTHING;

INSERT INTO roles (role_name)
SELECT DISTINCT role
FROM users
WHERE role IS NOT NULL
ON CONFLICT (role_name) DO NOTHING;

INSERT INTO user_role (user_id, role_id)
SELECT users.id, roles.id
FROM users
JOIN roles ON roles.role_name = users.role
WHERE users.role IS NOT NULL
ON CONFLICT (user_id, role_id) DO NOTHING;

INSERT INTO permissions (permission_name, description) VALUES
    ('USER_READ', 'View users'),
    ('USER_WRITE', 'Create and update users'),
    ('ROLE_READ', 'View roles'),
    ('ROLE_WRITE', 'Create and update roles'),
    ('EVENT_READ', 'View events'),
    ('EVENT_WRITE', 'Create and update events')
ON CONFLICT (permission_name) DO NOTHING;

INSERT INTO role_permission (role_id, permission_id)
SELECT roles.id, permissions.id
FROM roles
CROSS JOIN permissions
WHERE roles.role_name = 'ADMIN'
ON CONFLICT (role_id, permission_id) DO NOTHING;

INSERT INTO role_permission (role_id, permission_id)
SELECT roles.id, permissions.id
FROM roles
JOIN permissions ON permissions.permission_name IN ('EVENT_READ')
WHERE roles.role_name IN ('LECTURER', 'STUDENT')
ON CONFLICT (role_id, permission_id) DO NOTHING;

ALTER TABLE users DROP COLUMN role;
